name: Release Please

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      skip_release:
        description: 'Skip release creation and only publish existing tag'
        required: false
        type: boolean
        default: false
      tag_name:
        description: 'Tag to publish (only used if skip_release is true)'
        required: false
        type: string

permissions:
  contents: write
  pull-requests: write
  issues: write
  id-token: write

jobs:
  validate-and-release:
    runs-on: ubuntu-latest
    if: ${{ !inputs.skip_release }}
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
        
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.2'
          channel: 'stable'
          
      - name: Install dependencies
        run: flutter pub get
        
      - name: Run build_runner
        run: dart run build_runner build --delete-conflicting-outputs
        
      - name: Analyze code
        run: dart analyze --fatal-infos
        
      - name: Run tests
        run: flutter test
        
      - name: Check publish warnings
        run: dart pub publish --dry-run
        
      - name: Release Please
        id: release
        uses: googleapis/release-please-action@v4
        with:
          config-file: .release-please-config.json
          manifest-file: .release-please-manifest.json

  publish-to-pub-dev:
    needs: [validate-and-release]
    runs-on: ubuntu-latest
    if: ${{ always() && (needs.validate-and-release.outputs.release_created == 'true' || inputs.skip_release == true) }}
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout at release tag
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.skip_release && inputs.tag_name || needs.validate-and-release.outputs.tag_name }}
        
      # Use Dart setup first for OIDC support
      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
        
      - name: Setup Flutter  
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.2'
          channel: 'stable'
        
      - name: Install dependencies
        run: flutter pub get
        
      - name: Generate required files
        run: dart run build_runner build --delete-conflicting-outputs
        
      - name: Verify generated files exist
        run: |
          if [ ! -f "lib/src/Model/features_model.g.dart" ]; then
            echo "Error: features_model.g.dart not generated"
            exit 1
          fi
          echo "Generated files verified successfully"
        
      - name: Publish to pub.dev
        run: dart pub publish --force
