name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  validate-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
        
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.2'
          channel: 'stable'
          
      - name: Install dependencies
        run: flutter pub get
        
      - name: Run build_runner
        run: dart run build_runner build --delete-conflicting-outputs
        
      - name: Analyze code
        run: dart analyze --fatal-infos
        
      - name: Run tests
        run: flutter test
        
      - name: Check publish warnings
        run: dart pub publish --dry-run
        
      - name: Release Please
        id: release
        uses: google-github-actions/release-please-action@v4
        with:
          config-file: .release-please-config.json
          manifest-file: .release-please-manifest.json 